mybatis:
  mapper-locations: classpath:mapping/*.xml
server:
  port: 8081
spring:
  redis:
    host: 39.106.127.76
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
    password: 13892009451


sharding:
  jdbc:
    datasource:
      names: ds1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mymmal_protal_user
        username: root
        password: 123456
    config:
      sharding:
        tables:
          user_info:
            actual-data-nodes: ds1.user_info  #\u6570\u636E\u8282\u70B9
            table-strategy:  #\u5206\u8868\u7B56\u7565
              inline:
                shardingColumn: id
                algorithm-expression: user_info
          user_password:
            actual-data-nodes: ds1.user_password  #\u6570\u636E\u8282\u70B9
            table-strategy:  #\u5206\u8868\u7B56\u7565
              inline:
                shardingColumn: id
                algorithm-expression: user_password

