package com.example.mymmal.dao;

import com.example.mymmal.dataobject.CategoryDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface CategoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Tue Jun 16 03:35:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Tue Jun 16 03:35:18 CST 2020
     */
    int insert(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Tue Jun 16 03:35:18 CST 2020
     */
    int insertSelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Tue Jun 16 03:35:18 CST 2020
     */
    CategoryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Tue Jun 16 03:35:18 CST 2020
     */
    int updateByPrimaryKeySelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Tue Jun 16 03:35:18 CST 2020
     */
    int updateByPrimaryKey(CategoryDO record);

    List<CategoryDO> selectCategoryChildrenByParentId(Integer categoryId);
}