package com.example.mymmal.dao;

import com.example.mymmal.dataobject.ShippingDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ShippingDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated Wed Jun 17 18:44:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated Wed Jun 17 18:44:25 CST 2020
     */
    int insert(ShippingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated Wed Jun 17 18:44:25 CST 2020
     */
    int insertSelective(ShippingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated Wed Jun 17 18:44:25 CST 2020
     */
    ShippingDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated Wed Jun 17 18:44:25 CST 2020
     */
    int updateByPrimaryKeySelective(ShippingDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated Wed Jun 17 18:44:25 CST 2020
     */
    int updateByPrimaryKey(ShippingDO record);

    int updateByShipping(ShippingDO shippingDO);

    List<ShippingDO> selectByUserId(@Param("userId")Integer userId);

}